import { Router } from "express";
import { createCaedec, deleteCaedec, getCaedec, updateCaedec } from '../controllers/caedec.controller.js';
import {authRequired} from "../middlewares/validateToken.js"

import { Caedec } from "../models/caedec.js";
import { sequelize } from '../config/database.js';

const router=Router()

router.get('/caedec', authRequired, getCaedec );
router.post('/caedec',authRequired, createCaedec );
router.delete('/caedec/:id', authRequired, deleteCaedec);
router.put('/caedec/:id', authRequired, updateCaedec);

//carga masiva
const registros = [
    { nombre : 'Cultivo de cereales ', actividad:'1111'},
    { nombre : 'Cultivo de oleaginosas', actividad:'1112'},
    { nombre : 'Cultivos sacarinos', actividad:'1113'},
    { nombre : 'Cultivo de plantas para la obtención de fibras', actividad:'1114'},
    { nombre : 'Cultivo forrajero (para el pastoreo o la henificación, forraje verde o ensilaje)', actividad:'1115'},
    { nombre : 'Otros cultivos ncp', actividad:'1119'},
    { nombre : 'Cultivo de hortalizas de raíz y tubérculo', actividad:'1121'},
    { nombre : 'Cultivo de hortalizas de flor y fruto', actividad:'1122'},
    { nombre : 'Cultivo de hortalizas de hoja', actividad:'1123'},
    { nombre : 'Cultivo de hortalizas de bulbo', actividad:'1124'},
    { nombre : 'Cultivo de legumbres', actividad:'1125'},
    { nombre : 'Cultivo de flores y plantas ornamentales', actividad:'1126'},
    { nombre : 'Producción de semillas y otras formas de propagación de cultivos agrícolas', actividad:'1127'},
    { nombre : 'Otros cultivos de hortalizas, legumbres y especialidades hortícolas y recolecciones ncp', actividad:'1129'},
    { nombre : 'Cultivo de frutas de carozo', actividad:'1131'},
    { nombre : 'Cultivo de frutas cítricas', actividad:'1132'},
    { nombre : 'Cultivo de frutas de pepita', actividad:'1133'},
    { nombre : 'Cultivo de frutas secas', actividad:'1134'},
    { nombre : 'Cultivos de plantas para bebidas y estimulantes', actividad:'1135'},
    { nombre : 'Cultivo de especias y de plantas aromáticas y medicinales', actividad:'1136'},
    { nombre : 'Otras frutas cultivadas ncp', actividad:'1139'},
    { nombre : 'Caza  y captura de animales vivos y repoblación  de animales de caza y servicios conexos', actividad:'2001'},
    { nombre : 'Servicios para la caza', actividad:'2002'},
    { nombre : 'Extracción de productos forestales de bosques cultivados', actividad:'3001'},
    { nombre : 'Extracción de productos forestales de bosques nativos', actividad:'3002'},
    { nombre : 'Recolección de productos forestales silvestres', actividad:'3003'},
    { nombre : 'Servicios forestales de extracción de madera', actividad:'3004'},
    { nombre : 'Otros servicios forestales', actividad:'3009'},
    { nombre : 'Pesca  lacustre', actividad:'5001'},
    { nombre : 'Pesca fluvial', actividad:'5002'},
    { nombre : 'Explotación de criaderos de peces y granjas piscícolas', actividad:'5003'},
    { nombre : 'Actividades de servicios relacionadas con la pesca', actividad:'5004'},
    { nombre : 'Extracción y aglomeración de carbón de piedra', actividad:'10100'},
    { nombre : 'Extracción y aglomeración de lignito', actividad:'10200'},
    { nombre : 'Extracción y aglomeración de turba', actividad:'10300'},
    { nombre : 'Extracción de petróleo crudo y gas natural', actividad:'11100'},
    { nombre : 'Actividades de servicios relacionadas con la extracción de petróleo y gas, excepto las actividades de prospección', actividad:'11200'},
    { nombre : 'Extracción de minerales de uranio y torio', actividad:'12000'},
    { nombre : 'Extracción de minerales de hierro', actividad:'13100'},
    { nombre : 'Extracción de minerales metálicos no ferrosos, excepto los minerales de uranio y torio', actividad:'13201'},
    { nombre : 'Extracción de metales preciosos', actividad:'13202'},
    { nombre : 'Extracción de piedras', actividad:'14101'},
    { nombre : 'Extracción de arenas', actividad:'14102'},
    { nombre : 'Extracción de arcilla ', actividad:'14103'},
    { nombre : 'Extracción de piedras ornamentales', actividad:'14104'},
    { nombre : 'Extracción de minerales para la fabricación de abonos', actividad:'14211'},
    { nombre : 'Extracción de minerales para la fabricación de productos químicos', actividad:'14212'},
    { nombre : 'Extracción de sal', actividad:'14220'},
    { nombre : 'Explotación de otras minas y canteras ncp', actividad:'14290'},
    { nombre : 'Matanza de ganado bovino y procesamiento de su carne', actividad:'15111'},
    { nombre : 'Producción y procesamiento de carne de aves de corral', actividad:'15112'},
    { nombre : 'Elaboración de fiambres y embutidos', actividad:'15113'},
    { nombre : 'Matanza de ganado excepto el bovino y procesamiento de su carne', actividad:'15114'},
    { nombre : 'Elaboración de subproductos cárnicos ncp', actividad:'15119'},
    { nombre : 'Elaboración y conservación de pescado y productos de pescado', actividad:'15120'},
    { nombre : 'Preparación de conservas de frutas, hortalizas y legumbres', actividad:'15131'},
    { nombre : 'Elaboración de jugos naturales y sus concentrados, de frutas, hortalizas y legumbres', actividad:'15132'},
    { nombre : 'Elaboración de pulpas, jaleas, dulces y mermeladas obtenidos por cocción', actividad:'15133'},
    { nombre : 'Elaboración y preparación de frutas, hortalizas y legumbres deshidratadas o desecadas', actividad:'15134'},
    { nombre : 'Elaboración de aceites y grasas vegetales sin refinar y subproductos', actividad:'15141'},
    { nombre : 'Elaboración de aceites y grasas vegetales refinadas y subproductos', actividad:'15142'},
    { nombre : 'Preparación de tortas y producción de harinas y productos residuales de la producción de aceite', actividad:'15143'},
    { nombre : 'Elaboración de leches y productos lácteos', actividad:'15201'},
    { nombre : 'Elaboración de helados', actividad:'15202'},
    { nombre : 'Elaboración de quesos', actividad:'15203'},
    { nombre : 'Preparación y molienda de trigo', actividad:'15311'},
    { nombre : 'Preparación de arroz', actividad:'15312'},
    { nombre : 'Preparación y molienda de otros cereales ', actividad:'15313'},
    { nombre : 'Elaboración de alimentos mediante  el tostado o insuflación de granos de cereales', actividad:'15314'},
    { nombre : 'Elaboración de alimentos y productos derivados del almidón', actividad:'15320'},
    { nombre : 'Elaboración de alimentos preparados para animales', actividad:'15330'},
    { nombre : 'Elaboración de pan', actividad:'15411'},
    { nombre : 'Elaboración de galletas', actividad:'15412'},
    { nombre : 'Elaboración de otros productos de panadería y pastelería ncp', actividad:'15419'},
    { nombre : 'Elaboración de azúcar', actividad:'15420'},
    { nombre : 'Elaboración de cacao y productos de cacao', actividad:'15431'},
    { nombre : 'Elaboración de chocolates y productos de chocolate', actividad:'15432'},
    { nombre : 'Elaboración de productos de confitería', actividad:'15433'},
    { nombre : 'Elaboración de pastas alimenticias secas', actividad:'15441'},
    { nombre : 'Elaboración de pastas rellenas, cocidas o sin cocer y otros productos similares', actividad:'15442'},
    { nombre : 'Tostado, torrado y molienda de café', actividad:'15491'},
    { nombre : 'Elaboración de té, hierbas aromáticas y especias', actividad:'15492'},
    { nombre : 'Elaboración de productos alimenticios ncp', actividad:'15499'},
    { nombre : 'Destilación de alcohol etílico', actividad:'15511'},
    { nombre : 'Destilación, rectificación y mezclas de bebidas espirituosas', actividad:'15512'},
    { nombre : 'Elaboración de vinos, bebidas fermentadas pero no destiladas', actividad:'15521'},
    { nombre : 'Elaboración de bebidas malteadas y de malta', actividad:'15530'},
    { nombre : 'Elaboración de bebidas gaseosas', actividad:'15541'},
    { nombre : 'Elaboración de aguas minerales', actividad:'15542'},
    { nombre : 'Elaboración de hielo y otras bebidas no alcohólicas', actividad:'15543'},
    { nombre : 'Elaboración de productos de tabaco', actividad:'16000'},
    { nombre : 'Preparación, cardado y peinado de fibras textiles', actividad:'17111'},
    { nombre : 'Fabricación de hilados e hilos para tejido y costura', actividad:'17112'},
    { nombre : 'Fabricación de tejidos de fibras textiles incluso sus mezclas', actividad:'17113'},
    { nombre : 'Acabado de productos textiles', actividad:'17120'},
    { nombre : 'Fabricación de artículos confeccionados de materiales textiles, excepto prendas de vestir', actividad:'17210'},
    { nombre : 'Fabricación de tapices y alfombras', actividad:'17220'},
    { nombre : 'Fabricación de cuerdas, cordeles, bramantes y redes', actividad:'17230'},
    { nombre : 'Fabricación de otros productos textiles ncp', actividad:'17290'},
    { nombre : 'Fabricación de medias', actividad:'17301'},
    { nombre : 'Fabricación de chompas y artículos similares de punto', actividad:'17302'},
    { nombre : 'Fabricación de tejidos y artículos de punto ncp', actividad:'17309'},
    { nombre : 'Fabricación de prendas de vestir confeccionadas, para hombres, mujeres y niños', actividad:'18101'},
    { nombre : 'Fabricación de ropa de trabajo, uniformes y guardapolvos', actividad:'18102'},
    { nombre : 'Fabricación de ropa deportiva', actividad:'18103'},
    { nombre : 'Fabricación de prendas de vestir de cuero y otras prendas ncp ', actividad:'18109'},
    { nombre : 'Adobo y teñido de pieles; fabricación de artículos de piel ', actividad:'18200'},
    { nombre : 'Curtido de cueros', actividad:'19110'},
    { nombre : 'Fabricación de artículos de marroquinería, talabartería', actividad:'19120'},
    { nombre : 'Fabricación de calzado de cuero, excepto ortopédico y de asbesto', actividad:'19201'},
    { nombre : 'Fabricación de calzado de tela, plástico, goma, caucho y otros materiales, excepto calzado ortopédico y de asbesto', actividad:'19202'},
    { nombre : 'Fabricación de partes de calzado', actividad:'19203'},
    { nombre : 'Aserrado y cepillado de madera', actividad:'20100'},
    { nombre : 'Fabricación de hojas de madera para enchapado; de tableros contrachapados, tableros laminados, tableros de partículas y otros tableros y paneles', actividad:'20210'},
    { nombre : 'Fabricación de partes y piezas de carpintería para edificios y construcciones', actividad:'20220'},
    { nombre : 'Fabricación de recipientes de madera', actividad:'20230'},
    { nombre : 'Fabricación de otros productos de madera; de artículos de corcho, paja y materiales trenzables ncp', actividad:'20290'},
    { nombre : 'Fabricación de pasta de madera, papel y cartón', actividad:'21010'},
    { nombre : 'Fabricación de papel y cartón ondulado y de envases de papel y cartón', actividad:'21020'},
    { nombre : 'Fabricación de artículos de papel de uso doméstico e higiénico', actividad:'21091'},
    { nombre : 'Fabricación  de otros artículos de papel y cartón ncp', actividad:'21099'},
    { nombre : 'Edición de libros, folletos, partituras y otras publicaciones', actividad:'22110'},
    { nombre : 'Edición de periódicos, revistas y publicaciones periódicas', actividad:'22120'},
    { nombre : 'Edición de grabaciones', actividad:'22130'},
    { nombre : 'Otras actividades de edición', actividad:'22190'},
    { nombre : 'Actividades de impresión', actividad:'22210'},
    { nombre : 'Actividades de servicios relacionadas con la impresión', actividad:'22220'},
    { nombre : 'Reproducción de grabaciones', actividad:'22300'},
    { nombre : 'Fabricación de productos de hornos de coque', actividad:'23100'},
    { nombre : 'Fabricación de productos de la refinación del petróleo', actividad:'23200'},
    { nombre : 'Elaboración de combustible nuclear', actividad:'23300'},
    { nombre : 'Fabricación de gases industriales', actividad:'24111'},
    { nombre : 'Fabricación de sustancias químicas básicas ', actividad:'24112'},
    { nombre : 'Fabricación de abonos y compuestos de nitrógeno', actividad:'24120'},
    { nombre : 'Fabricación de plásticos en formas primarias y de caucho sintético', actividad:'24130'},
    { nombre : 'Fabricación de plaguicidas y otros productos químicos de uso agropecuario', actividad:'24210'},
    { nombre : 'Fabricación de pinturas, barnices y productos de revestimiento similares, tintas de imprenta y masillas', actividad:'24220'},
    { nombre : 'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos', actividad:'24230'},
    { nombre : 'Fabricación de jabones y detergentes', actividad:'24241'},
    { nombre : 'Fabricación de cosméticos, perfumes, productos de higiene y tocador', actividad:'24242'},
    { nombre : 'Fabricación de preparados para limpiar y pulir', actividad:'24243'},
    { nombre : 'Fabricación de otros productos químicos ncp', actividad:'24290'},
    { nombre : 'Fabricación de fibras manufacturadas', actividad:'24300'},
    { nombre : 'Fabricación de cubiertas y cámaras de caucho; recauchutado y renovación de cubiertas de caucho', actividad:'25110'},
    { nombre : 'Fabricación de otros productos de caucho', actividad:'25190'},
    { nombre : 'Fabricación de envases plásticos', actividad:'25201'},
    { nombre : 'Fabricación de productos plásticos en formas básicas y artículos de plástico ncp ', actividad:'25209'},
    { nombre : 'Fabricación de envases de vidrio', actividad:'26101'},
    { nombre : 'Fabricación de vidrio', actividad:'26102'},
    { nombre : 'Fabricación de productos de vidrio ncp', actividad:'26109'},
    { nombre : 'Fabricación de artículos de cerámica de uso doméstico, sanitario y ornamental', actividad:'26911'},
    { nombre : 'Fabricación de otros artículos de cerámica no refractaria para uso no estructural', actividad:'26912'},
    { nombre : 'Fabricación  de productos de cerámica refractaria', actividad:'26920'},
    { nombre : 'Fabricación de productos de arcilla y cerámica no refractarias para uso estructural', actividad:'26930'},
    { nombre : 'Fabricación de cemento', actividad:'26941'},
    { nombre : 'Fabricación de cal y yeso', actividad:'26942'},
    { nombre : 'Fabricación de artículos de hormigón, cemento y  yeso', actividad:'26950'},
    { nombre : 'Corte, tallado y acabado de la piedra', actividad:'26960'},
    { nombre : 'Fabricación de otros productos minerales no metálicos ncp', actividad:'26990'},
    { nombre : 'Industrias básicas de hierro y acero', actividad:'27100'},
    { nombre : 'Producción de metales comunes no ferrosos en formas primarias', actividad:'27201'},
    { nombre : 'Producción de metales preciosos en formas primarias', actividad:'27202'},
    { nombre : 'Fundición de hierro y acero', actividad:'27310'},
    { nombre : 'Fundición de metales no ferrosos', actividad:'27320'},
    { nombre : 'Fabricación de productos metálicos para uso estructural', actividad:'28110'},
    { nombre : 'Fabricación de tanques, depósitos y recipientes de metal', actividad:'28120'},
    { nombre : 'Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central', actividad:'28130'},
    { nombre : 'Forja, prensado, estampado y laminado de metales; pulvimetalurgia', actividad:'28910'},
    { nombre : 'Tratamiento y revestimiento de metales; obras de ingeniería mecánica en general realizadas a cambio de una retribución o contrata', actividad:'28920'},
    { nombre : 'Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería', actividad:'28930'},
    { nombre : 'Fabricación de envases de productos metálicos', actividad:'28991'},
    { nombre : 'Fabricación de productos metálicos ncp', actividad:'28999'},
    { nombre : 'Fabricación de motores y turbinas, excepto motores para aeronaves, vehículos automotores y motocicletas', actividad:'29110'},
    { nombre : 'Fabricación de bombas, compresores, grifos y válvulas', actividad:'29120'},
    { nombre : 'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión', actividad:'29130'},
    { nombre : 'Fabricación de hornos; hogares y quemadores', actividad:'29140'},
    { nombre : 'Fabricación de equipo de elevación y manipulación', actividad:'29150'},
    { nombre : 'Fabricación de otros tipos de maquinaria de uso general', actividad:'29190'},
    { nombre : 'Fabricación de maquinaria agropecuaria y forestal', actividad:'29210'},
    { nombre : 'Fabricación  de máquinas herramienta', actividad:'29220'},
    { nombre : 'Fabricación  de maquinaria metalúrgica', actividad:'29230'},
    { nombre : 'Fabricación de maquinaria para la explotación de minas y canteras y para obras de construcción', actividad:'29240'},
    { nombre : 'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco', actividad:'29250'},
    { nombre : 'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros', actividad:'29260'},
    { nombre : 'Fabricación de armas y municiones', actividad:'29270'},
    { nombre : 'Fabricación de otros tipos de maquinaria de uso  especial', actividad:'29290'},
    { nombre : 'Fabricación de aparatos de uso doméstico ncp', actividad:'29300'},
    { nombre : 'Fabricación de maquinaria de oficina, contabilidad e informática', actividad:'30000'},
    { nombre : 'Fabricación de motores, generadores y transformadores eléctricos', actividad:'31100'},
    { nombre : 'Fabricación de aparatos de distribución y control de energía eléctrica', actividad:'31200'},
    { nombre : 'Fabricación de hilos y cables aislados', actividad:'31300'},
    { nombre : 'Fabricación de acumuladores y de pilas y baterías primarias', actividad:'31400'},
    { nombre : 'Fabricación de lámparas eléctricas y equipo de iluminación', actividad:'31500'},
    { nombre : 'Fabricación de otros tipos de equipo eléctrico ncp', actividad:'31900'},
    { nombre : 'Fabricación de tubos, válvulas y de otros componentes electrónicos', actividad:'32100'},
    { nombre : 'Fabricación  de transmisores de radio y televisión y de aparatos para telefonía y telegrafía con hilos', actividad:'32200'},
    { nombre : 'Fabricación de receptores de radio y televisión, aparatos de grabación y reproducción de sonido, vídeo y productos conexos', actividad:'32300'},
    { nombre : 'Fabricación de equipo médico y quirúrgico y de aparatos ortopédicos', actividad:'33110'},
    { nombre : 'Fabricación de instrumentos y aparatos para medir, verificar, ensayar, navegar y otros fines, excepto el equipo de control de procesos industriales', actividad:'33120'},
    { nombre : 'Fabricación de equipo de control de procesos industriales', actividad:'33130'},
    { nombre : 'Fabricación de instrumentos de óptica y equipo fotográfico', actividad:'33200'},
    { nombre : 'Fabricación de relojes', actividad:'33300'},
    { nombre : 'Fabricación de vehículos automotores', actividad:'34100'},
    { nombre : 'Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques', actividad:'34200'},
    { nombre : 'Fabricación de partes, piezas y accesorios para vehículos automotores y sus motores', actividad:'34300'},
    { nombre : 'Construcción y reparación de buques', actividad:'35110'},
    { nombre : 'Construcción y reparación de embarcaciones de recreo y deporte', actividad:'35120'},
    { nombre : 'Fabricación de locomotoras y de material rodante para ferrocarriles y tranvías', actividad:'35200'},
    { nombre : 'Fabricación de aeronaves y naves espaciales', actividad:'35300'},
    { nombre : 'Fabricación de motocicletas', actividad:'35910'},
    { nombre : 'Fabricación de bicicletas y de sillones de ruedas para inválidos', actividad:'35920'},
    { nombre : 'Fabricación de otros tipos de equipo de transporte ncp', actividad:'35990'},
    { nombre : 'Fabricación de muebles y partes de muebles, principalmente de madera', actividad:'36101'},
    { nombre : 'Fabricación de muebles y partes de muebles, principalmente de metal', actividad:'36102'},
    { nombre : 'Fabricación de muebles, excepto los que son principalmente de madera y metálicos', actividad:'36103'},
    { nombre : 'Fabricación de somieres y colchones', actividad:'36104'},
    { nombre : 'Fabricación de joyas y artículos conexos', actividad:'36910'},
    { nombre : 'Fabricación de instrumentos de música', actividad:'36920'},
    { nombre : 'Fabricación de artículos de deporte', actividad:'36930'},
    { nombre : 'Fabricación de juegos y juguetes', actividad:'36940'},
    { nombre : 'Otras industrias manufactureras ncp', actividad:'36990'},
    { nombre : 'Reciclamiento de desperdicios y  desechos metálicos', actividad:'37100'},
    { nombre : 'Reciclamiento de desperdicios y  desechos no metálicos', actividad:'37200'},
    { nombre : 'Producción de energía hidráulica', actividad:'40101'},
    { nombre : 'Producción de energía térmica convencional', actividad:'40102'},
    { nombre : 'Transporte de energía eléctrica', actividad:'40103'},
    { nombre : 'Distribución de energía eléctrica', actividad:'40104'},
    { nombre : 'Producción de energía eléctrica ncp', actividad:'40109'},
    { nombre : 'Producción de gas', actividad:'40201'},
    { nombre : 'Distribución de combustibles gaseosos', actividad:'40202'},
    { nombre : 'Suministro de vapor y agua caliente', actividad:'40300'},
    { nombre : 'Captación, depuración y distribución de agua de fuentes subterráneas', actividad:'41001'},
    { nombre : 'Captación, depuración y distribución de agua de fuentes superficiales', actividad:'41002'},
    { nombre : 'Demolición y derribo de edificios y otras estructuras', actividad:'45101'},
    { nombre : 'Perforación, excavación, pruebas, sondeo y muestreo de terreno con fines de construcción', actividad:'45102'},
    { nombre : 'Movimiento de suelos y preparación de terreno relleno y desmonte para obras ncp', actividad:'45109'},
    { nombre : 'Construcción, reforma y reparación de edificios', actividad:'45201'},
    { nombre : 'Construcción, reforma y reparación de obras de infraestructura de transporte', actividad:'45202'},
    { nombre : 'Construcción de obras de ingeniería civil ncp', actividad:'45209'},
    { nombre : 'Instalación de ascensores, montacargas y escaleras mecánicas', actividad:'45301'},
    { nombre : 'Instalaciones y mantenimiento eléctrico y electrónicos', actividad:'45302'},
    { nombre : 'Instalaciones de sistemas de acondicionamiento de ambientes', actividad:'45303'},
    { nombre : 'Instalación de aislamiento térmico, acústico, hídrico y antivibratorio', actividad:'45304'},
    { nombre : 'Instalaciones de estaciones de telecomunicaciones y de radar', actividad:'45305'},
    { nombre : 'Instalaciones de plomería, desagües, gas, agua, sanitarios, con sus artefactos conexos', actividad:'45306'},
    { nombre : 'Reparaciones relacionadas con la instalación y acondicionamiento de edificios y obras de ingeniería civil ', actividad:'45307'},
    { nombre : 'Instalaciones de carpintería, herrería  de obra artística', actividad:'45401'},
    { nombre : 'Trabajos de revestimiento, pulimento de paredes y pisos', actividad:'45402'},
    { nombre : 'Colocación de vidrios y cristales en obra', actividad:'45403'},
    { nombre : 'Pintura y trabajos de decoración', actividad:'45404'},
    { nombre : 'Trabajos de reparación relacionadas con la terminación de edificios', actividad:'45405'},
    { nombre : 'Otros trabajos de terminación de edificios ncp', actividad:'45409'},
    { nombre : 'Alquiler de equipo de construcción y demolición dotado de operarios', actividad:'45500'},
    { nombre : 'Venta de vehículos automotores, nuevos', actividad:'50101'},
    { nombre : 'Venta de vehículos automotores, usados', actividad:'50102'},
    { nombre : 'Mantenimiento y reparación del motor; mecánica integral', actividad:'50201'},
    { nombre : 'Lavado de automotores automático y manual', actividad:'50202'},
    { nombre : 'Reparación de cámaras de cubiertas', actividad:'50203'},
    { nombre : 'Tapizado y retapizado', actividad:'50204'},
    { nombre : 'Reparaciones eléctricas, del tablero e instrumental', actividad:'50205'},
    { nombre : 'Reparación, colocación y pintado de carrocerías; guardabarros y protecciones exteriores', actividad:'50206'},
    { nombre : 'Mantenimiento y reparación de vehículos ncp', actividad:'50209'},
    { nombre : 'Venta de partes, piezas y accesorios de vehículos automotores', actividad:'50300'},
    { nombre : 'Venta de motocicletas y de sus partes, piezas y accesorios', actividad:'50401'},
    { nombre : 'Mantenimiento y reparación de motocicletas', actividad:'50402'},
    { nombre : 'Venta al por menor de combustible para automotores', actividad:'50501'},
    { nombre : 'Venta al por menor de lubricantes, grasas y refrigerantes para automotores', actividad:'50502'},
    { nombre : 'Venta al por mayor de intermediarios en comisión o consignación de productos agrícolas y pecuarios', actividad:'51101'},
    { nombre : 'Venta al por mayor de intermediarios en comisión o consignación de café', actividad:'51102'},
    { nombre : 'Venta al por mayor de intermediarios en comisión o consignación de alimentos, bebidas y tabaco', actividad:'51103'},
    { nombre : 'Venta al por mayor de intermediarios en comisión o consignación de productos textiles, prendas de vestir, calzado excepto el ortopédico,  artículos de marroquinería, paraguas y similares y productos d', actividad:'51104'},
    { nombre : 'Venta al por mayor de intermediarios en comisión o consignación de  madera y materiales para la construcción', actividad:'51105'},
    { nombre : 'Venta al por mayor de intermediarios en comisión o consignación de productos farmacéuticos, medicinales y cosméticos', actividad:'51106'},
    { nombre : 'Venta al por mayor de intermediarios en comisión o consignación de  maquinaria, equipo profesional, industrial y comercial', actividad:'51107'},
    { nombre : 'Venta al por mayor de intermediarios en comisión o consignación de papel, cartón, libros, revistas, diarios, materiales de embalaje y artículos de librería', actividad:'51108'},
    { nombre : 'Venta al por mayor de intermediarios en comisión o consignación de  mercaderías ncp', actividad:'51109'},
    { nombre : 'Venta al por mayor de materias primas agropecuarias y de la silvicultura', actividad:'51211'},
    { nombre : 'Venta al por mayor de animales vivos', actividad:'51212'},
    { nombre : 'Venta al por mayor de cueros y pieles', actividad:'51213'},
    { nombre : 'Venta al por mayor y empaque de frutas, legumbres y hortalizas frescas', actividad:'51221'},
    { nombre : 'Venta al por mayor de productos lácteos', actividad:'51222'},
    { nombre : 'Venta al por mayor de huevos, aceites y grasas comestibles', actividad:'51223'},
    { nombre : 'Venta al por mayor de carnes rojas, menudencias; productos de granja y embutidos', actividad:'51224'},
    { nombre : 'Venta al por mayor de pan, productos de confitería, pastas frescas', actividad:'51225'},
    { nombre : 'Venta al por mayor de café, té, cacao y especias', actividad:'51226'},
    { nombre : 'Venta al por mayor de bebidas, cigarrillos y  tabaco', actividad:'51227'},
    { nombre : 'Venta al por mayor de azúcar, dulces, chocolates, golosinas  y otros, excepto cigarrillos', actividad:'51228'},
    { nombre : 'Venta al por mayor de productos alimenticios ncp', actividad:'51229'},
    { nombre : 'Venta al por mayor  de productos textiles excepto prendas de vestir', actividad:'51311'},
    { nombre : 'Venta al por mayor de confecciones para el hogar', actividad:'51312'},
    { nombre : 'Venta al por mayor de prendas y accesorios de vestir', actividad:'51313'},
    { nombre : 'Venta al por mayor de calzado, excepto el ortopédico, artículos de marroquinería, y similares', actividad:'51314'},
    { nombre : 'Venta al por mayor de artículos de cuero', actividad:'51315'},
    { nombre : 'Venta al por mayor de libros y revistas', actividad:'51321'},
    { nombre : 'Venta al por mayor de periódicos', actividad:'51322'},
    { nombre : 'Venta al por mayor de papel, cartón, materiales de embalaje y artículos de librería ncp', actividad:'51329'},
    { nombre : 'Venta al por mayor de muebles, artículos de mimbre y corcho; colchones y somieres', actividad:'51331'},
    { nombre : 'Venta al por mayor de artículos de iluminación ', actividad:'51332'},
    { nombre : 'Venta al por mayor de artículos de bazar y menaje', actividad:'51333'},
    { nombre : 'Venta al por mayor de artefactos para el hogar, eléctricos, a gas, kerosene u otros combustibles', actividad:'51334'},
    { nombre : 'Venta al por mayor de instrumentos musicales', actividad:'51335'},
    { nombre : 'Venta al por mayor de equipos de sonido, casetes de audio y video y discos ', actividad:'51336'},
    { nombre : 'Venta al por mayor de artículos para el hogar ncp', actividad:'51339'},
    { nombre : 'Venta al por mayor de productos farmacéuticos y medicinales', actividad:'51341'},
    { nombre : 'Venta al por mayor de productos de perfumería y de belleza', actividad:'51342'},
    { nombre : 'Venta al por mayor de instrumental médico y odontológico, y otros artículos ortopédicos', actividad:'51343'},
    { nombre : 'Venta al por mayor de productos veterinarios', actividad:'51344'},
    { nombre : 'Venta al por mayor de artículos de óptica', actividad:'51351'},
    { nombre : 'Venta al por mayor de artículos de fotografía', actividad:'51352'},
    { nombre : 'Venta al por mayor de artículos de relojería', actividad:'51353'},
    { nombre : 'Venta al por mayor de artículos de joyería y fantasías', actividad:'51354'},
    { nombre : 'Venta al por mayor de materiales y productos de limpieza', actividad:'51391'},
    { nombre : 'Venta al por mayor de juguetes y artículos de cotillón', actividad:'51392'},
    { nombre : 'Venta al por mayor de artículos de esparcimiento y deportes', actividad:'51393'},
    { nombre : 'Venta al por mayor de bicicletas y rodados similares', actividad:'51394'},
    { nombre : 'Venta al por mayor de papeles para pared, revestimientos y alfombras para pisos, y artículos similares para la decoración', actividad:'51395'},
    { nombre : 'Venta al por mayor de artículos artesanales', actividad:'51396'},
    { nombre : 'Venta al por mayor de artículos de uso doméstico y/o personal ncp', actividad:'51399'},
    { nombre : 'Venta al por mayor de combustibles y lubricantes para automotores', actividad:'51411'},
    { nombre : 'Venta al por mayor de combustibles y lubricantes excepto para automotores: gas en garrafas, leña y carbón', actividad:'51412'},
    { nombre : 'Venta al por mayor de metales y minerales metalíferos', actividad:'51420'},
    { nombre : 'Venta al por mayor de materiales de construcción', actividad:'51431'},
    { nombre : 'Venta al por mayor de madera sin desbastar y productos primarios', actividad:'51432'},
    { nombre : 'Venta al por mayor de artículos de ferretería, fontanería y calefacción', actividad:'51433'},
    { nombre : 'Venta al por mayor de pintura y productos conexos', actividad:'51434'},
    { nombre : 'Venta al por mayor de cristales, espejos y mamparas', actividad:'51435'},
    { nombre : 'Venta al por mayor de productos químicos', actividad:'51491'},
    { nombre : 'Venta al por mayor de desperdicios y desechos metálicos', actividad:'51492'},
    { nombre : 'Venta al por mayor de desperdicios y desechos no metálicos', actividad:'51493'},
    { nombre : 'Venta al por mayor de otros productos intermedios ncp', actividad:'51499'},
    { nombre : 'Venta al por mayor de máquinas, equipos e implementos de uso  agropecuario', actividad:'51501'},
    { nombre : 'Venta al por mayor de máquinas, equipos e implementos de uso en la minería.', actividad:'51502'},
    { nombre : 'Venta al por mayor de máquinas, equipos e implementos de uso en la industria manufacturera', actividad:'51503'},
    { nombre : 'Venta al por mayor de máquinas y equipos de construcción e ingeniería civil', actividad:'51504'},
    { nombre : 'Venta al por mayor de máquinas, equipos e implementos de uso médico y paramédico', actividad:'51505'},
    { nombre : 'Venta al por mayor de equipos informáticos y máquinas electrónicas de escribir y calcular ', actividad:'51506'},
    { nombre : 'Venta al por mayor de máquinas y equipos de comunicaciones, control y seguridad', actividad:'51507'},
    { nombre : 'Venta al por mayor de máquinas, equipos e implementos de uso especial ncp ', actividad:'51509'},
    { nombre : 'Venta al por mayor de otros productos', actividad:'51900'},
    { nombre : 'Venta al por menor en supermercados con surtido compuesto y predominio de productos alimenticios, bebidas y tabaco', actividad:'52111'},
    { nombre : 'Venta al por menor en almacenes con surtido compuesto y predominio de productos alimenticios y bebidas y tabaco', actividad:'52112'},
    { nombre : 'Venta al por menor en tiendas de barrio  con surtido compuesto y predominio de productos alimenticios, bebidas y tabaco', actividad:'52113'},
    { nombre : 'Venta al por menor de otros productos en almacenes no especializados', actividad:'52190'},
    { nombre : 'Venta al por menor y empaque de frutas, legumbres y hortalizas frescas', actividad:'52201'},
    { nombre : 'Venta al por menor de productos lácteos', actividad:'52202'},
    { nombre : 'Venta al por menor de huevos, aceites y grasas comestibles', actividad:'52203'},
    { nombre : 'Venta al por menor de carnes rojas, menudencias; productos de granja y embutidos', actividad:'52204'},
    { nombre : 'Venta al por menor de pan, productos de confitería, pastas frescas', actividad:'52205'},
    { nombre : 'Venta al por menor de café, té, cacao y especias', actividad:'52206'},
    { nombre : 'Venta al por menor de bebidas, cigarrillos y  tabaco', actividad:'52207'},
    { nombre : 'Venta al por menor de azúcar, dulces, chocolates, golosinas y otros, excepto cigarrillos', actividad:'52208'},
    { nombre : 'Venta al por menor de alimentos ncp en almacenes especializados', actividad:'52209'},
    { nombre : 'Venta al por menor de productos farmacéuticos y medicinales', actividad:'52311'},
    { nombre : 'Venta al por menor de cosméticos, artículos de tocador y perfumería', actividad:'52312'},
    { nombre : 'Venta al por menor de artículos médicos, odontológicos y aparatos ortopédicos', actividad:'52313'},
    { nombre : 'Venta al por menor de productos veterinarios', actividad:'52314'},
    { nombre : 'Venta al por menor  de productos textiles, excepto prendas de vestir', actividad:'52321'},
    { nombre : 'Venta al por menor de confecciones para el hogar', actividad:'52322'},
    { nombre : 'Venta al por menor de prendas y accesorios de vestir', actividad:'52323'},
    { nombre : 'Venta al por menor de calzado, excepto el ortopédico, artículos de marroquinería, y similares', actividad:'52324'},
    { nombre : 'Venta al por menor de artículos de cuero', actividad:'52325'},
    { nombre : 'Venta al por menor de muebles, artículos de mimbre y corcho; colchones y somiers', actividad:'52331'},
    { nombre : 'Venta al por menor de artículos de iluminación', actividad:'52332'},
    { nombre : 'Venta al por menor de artículos de bazar y menaje', actividad:'52333'},
    { nombre : 'Venta al por menor de artefactos para el hogar, eléctricos, a gas, kerosene u otros combustibles', actividad:'52334'},
    { nombre : 'Venta al por menor de instrumentos musicales ', actividad:'52335'},
    { nombre : 'Venta al por menor de equipos de sonido, casetes de audio, vídeo y discos ', actividad:'52336'},
    { nombre : 'Venta al por menor de artículos para el hogar ncp', actividad:'52339'},
    { nombre : 'Venta al por menor de materiales de construcción', actividad:'52341'},
    { nombre : 'Venta al por menor de artículos de ferretería, fontanería y calefacción', actividad:'52342'},
    { nombre : 'Venta al por menor de pintura y productos conexos', actividad:'52343'},
    { nombre : 'Venta al por menor de cristales, espejos y mamparas', actividad:'52344'},
    { nombre : 'Venta al por menor de libros, revistas ', actividad:'52351'},
    { nombre : 'Venta al por menor de periódicos', actividad:'52352'},
    { nombre : 'Venta al por menor de papel, cartón, materiales de embalaje y artículos de librería ncp', actividad:'52359'},
    { nombre : 'Venta al por menor de maquinaria de oficina y contabilidad', actividad:'52361'},
    { nombre : 'Venta al por menor de equipos informáticos', actividad:'52362'},
    { nombre : 'Venta al por menor de máquinas y equipos de comunicaciones, control y seguridad', actividad:'52363'},
    { nombre : 'Venta al por menor de flores', actividad:'52371'},
    { nombre : 'Venta al por menor de plantas, semillas y abonos', actividad:'52372'},
    { nombre : 'Venta al por menor de animales domésticos', actividad:'52373'},
    { nombre : 'Venta al por menor de artículos de óptica ', actividad:'52381'},
    { nombre : 'Venta al por menor de artículos de fotografía', actividad:'52382'},
    { nombre : 'Venta al por menor de artículos de relojería', actividad:'52383'},
    { nombre : 'Venta al por menor de artículos de joyería y fantasías', actividad:'52384'},
    { nombre : 'Venta al por menor de materiales y productos de limpieza', actividad:'52391'},
    { nombre : 'Venta al por menor de juguetes y artículos de cotillón', actividad:'52392'},
    { nombre : 'Venta al por menor de artículos de esparcimiento y deportes', actividad:'52393'},
    { nombre : 'Venta al por menor de bicicletas y rodados similares', actividad:'52394'},
    { nombre : 'Venta al por menor de papeles para pared, revestimientos para pisos y artículos similares para la decoración', actividad:'52395'},
    { nombre : 'Venta al por menor de artículos artesanales', actividad:'52396'},
    { nombre : 'Venta al por menor de combustibles sólidos y líquidos', actividad:'52397'},
    { nombre : 'Venta al por menor de combustible gaseoso', actividad:'52398'},
    { nombre : 'Venta al por menor de otros productos en almacenes especializados ncp', actividad:'52399'},
    { nombre : 'Venta al por menor de muebles usados', actividad:'52401'},
    { nombre : 'Venta al por menor de libros, revistas y similares usados', actividad:'52402'},
    { nombre : 'Venta al por menor de prendas de vestir y productos  textiles usados', actividad:'52403'},
    { nombre : 'Venta al por menor en almacenes de artículos usados ncp', actividad:'52409'},
    { nombre : 'Venta al por menor en empresas de venta por correo', actividad:'52510'},
    { nombre : 'Venta al por menor en puestos de venta y mercados', actividad:'52520'},
    { nombre : 'Otros tipos de venta al por menor no realizada en almacenes', actividad:'52590'},
    { nombre : 'Venta al por menor de loterías, bingos y rifas', actividad:'52591'},
    { nombre : 'Reparación de calzados y artículos de marroquinería y otros artículos de cuero', actividad:'52601'},
    { nombre : 'Reparación de artículos eléctricos de uso doméstico', actividad:'52602'},
    { nombre : 'Reparación  y tapizado de muebles', actividad:'52603'},
    { nombre : 'Reparación de bicicletas, triciclos y otros', actividad:'52604'},
    { nombre : 'Reparación de efectos personales y enseres domésticos ncp', actividad:'52609'},
    { nombre : 'Servicios de alojamiento en hoteles', actividad:'55101'},
    { nombre : 'Servicios de alojamiento en residencias', actividad:'55102'},
    { nombre : 'Servicios de alojamiento en hospedajes y otros', actividad:'55103'},
    { nombre : 'Servicios de alojamiento en moteles', actividad:'55104'},
    { nombre : 'Servicios de expendio de comidas en establecimientos con servicio de mesa y/o en mostrador', actividad:'55201'},
    { nombre : 'Servicio de expendio de comidas exclusivo en churrasquerías', actividad:'55202'},
    { nombre : 'Servicio de expendio de comidas exclusivo en pollos broaster ', actividad:'55203'},
    { nombre : 'Servicio de expendio de comidas exclusivo en pescado ', actividad:'55204'},
    { nombre : 'Servicio, preparación y venta de comidas rápidas', actividad:'55205'},
    { nombre : 'Servicios de expendio de comidas en establecimientos fijos o móviles', actividad:'55206'},
    { nombre : 'Otros servicios de expendio de comidas ncp.', actividad:'55209'},
    { nombre : 'Servicios de expendio de bebidas alcohólicas en bares y cantinas', actividad:'55211'},
    { nombre : 'Servicios de expendio de bebidas alcohólicas en whiskerías', actividad:'55212'},
    { nombre : 'Servicios de expendio de bebidas alcohólicas en quintas y chicherías', actividad:'55213'},
    { nombre : 'Servicios de expendio de bebidas no alcohólicas ', actividad:'55214'},
    { nombre : 'Servicio de heladerías', actividad:'55215'},
    { nombre : 'Servicio de expendio de jugos, zumos y ensaladas de frutas', actividad:'55216'},
    { nombre : 'Servicios de expendio de bebidas en establecimientos fijos o móviles', actividad:'55217'},
    { nombre : 'Otros servicios de expendio de bebidas ncp', actividad:'55219'},
    { nombre : 'Servicio de transporte ferroviario', actividad:'60100'},
    { nombre : 'Servicio de transporte automotor urbano de pasajeros', actividad:'60211'},
    { nombre : 'Servicio de transporte automotor suburbano de pasajeros', actividad:'60212'},
    { nombre : 'Servicios de alquiler de automotores con conductor', actividad:'60221'},
    { nombre : 'Otros servicios de transporte no regular de pasajeros', actividad:'60222'},
    { nombre : 'Servicio de transporte automotor de carga por carretera', actividad:'60230'},
    { nombre : 'Servicio de transporte por tuberías', actividad:'60300'},
    { nombre : 'Transporte marítimo y de cabotaje ', actividad:'61100'},
    { nombre : 'Transporte por vías de navegación interiores', actividad:'61200'},
    { nombre : 'Servicio de transporte aéreo regular de pasajeros', actividad:'62101'},
    { nombre : 'Servicio de transporte aéreo regular de carga', actividad:'62102'},
    { nombre : 'Transporte no regular por vía aérea', actividad:'62200'},
    { nombre : 'Servicios de manipulación de la carga', actividad:'63010'},
    { nombre : 'Servicio de almacenamiento y depósito', actividad:'63020'},
    { nombre : 'Servicios de explotación de infraestructura; peajes y otros derechos', actividad:'63031'},
    { nombre : 'Servicios complementarios para el transporte aéreo', actividad:'63032'},
    { nombre : 'Servicios complementarios para el transporte por agua ', actividad:'63033'},
    { nombre : 'Servicios de agencias de viajes', actividad:'63041'},
    { nombre : 'Servicios complementarios de apoyo turístico', actividad:'63042'},
    { nombre : 'Servicio de apoyo y logística de agencias para el transporte de mercaderías', actividad:'63090'},
    { nombre : 'Servicios de correo nacional', actividad:'64110'},
    { nombre : 'Servicios de correo distinta a las actividades de correo nacional', actividad:'64120'},
    { nombre : 'Servicios de transmisión de datos y mensajes', actividad:'64201'},
    { nombre : 'Servicio de transmisión de radio y televisión', actividad:'64202'},
    { nombre : 'Servicios de transmisión de sonido, imágenes, datos u otra información ncp', actividad:'64209'},
    { nombre : 'Servicios de la banca central', actividad:'65110'},
    { nombre : 'Servicios de las entidades bancarias', actividad:'65191'},
    { nombre : 'Servicios de las cajas de ahorro y préstamo', actividad:'65192'},
    { nombre : 'Servicios de las cooperativas de ahorro y crédito', actividad:'65193'},
    { nombre : 'Arrendamiento financiero', actividad:'65910'},
    { nombre : 'Otros servicios de crédito', actividad:'65920'},
    { nombre : 'Otro tipo de servicios de intermediación financiera ncp', actividad:'65990'},
    { nombre : 'Servicio de planes de seguros de vida', actividad:'66010'},
    { nombre : 'Administración de fondos de jubilaciones y pensiones', actividad:'66020'},
    { nombre : 'Servicios de otros planes de seguros excepto de vida', actividad:'66030'},
    { nombre : 'Servicios de administración de mercados financieros', actividad:'67110'},
    { nombre : 'Servicios bursátiles de mediación o por cuenta de terceros', actividad:'67120'},
    { nombre : 'Servicios de casas y agencias de cambio', actividad:'67191'},
    { nombre : 'Otros servicios auxiliares de la intermediación financiera ncp', actividad:'67199'},
    { nombre : 'Servicios auxiliares a los servicios de seguros y de administración de fondos de jubilaciones y pensiones', actividad:'67201'},
    { nombre : 'Servicios auxiliares a los servicios de administración de fondos de jubilaciones y pensiones', actividad:'67202'},
    { nombre : 'Servicios inmobiliarios realizados por cuenta propia, con bienes propios o arrendados', actividad:'70100'},
    { nombre : 'Servicios inmobiliarios de compra, venta y alquiler', actividad:'70201'},
    { nombre : 'Servicios de administración inmobiliaria de bienes inmuebles', actividad:'70202'},
    { nombre : 'Servicios de promoción y asesoramiento en materia inmobiliaria', actividad:'70203'},
    { nombre : 'Alquiler de equipo de transporte por vía terrestre sin personal', actividad:'71110'},
    { nombre : 'Alquiler de equipo de transporte por vía acuática sin personal', actividad:'71120'},
    { nombre : 'Alquiler de equipo de transporte por vía aérea sin personal ni tripulación', actividad:'71130'},
    { nombre : 'Alquiler de maquinaria y equipo agropecuario sin personal', actividad:'71210'},
    { nombre : 'Alquiler de maquinaria y equipo de construcción e ingeniería civil sin personal', actividad:'71220'},
    { nombre : 'Alquiler de maquinaria y equipo de oficina (incluso computadoras)', actividad:'71230'},
    { nombre : 'Alquiler de otros tipos de maquinaria y equipo sin personal ncp', actividad:'71290'},
    { nombre : 'Alquiler de efectos personales y enseres domésticos ncp', actividad:'71300'},
    { nombre : 'Servicios de consultores en equipo de informática', actividad:'72100'},
    { nombre : 'Servicios de consultores en informática y suministro de programas de informática', actividad:'72200'},
    { nombre : 'Procesamiento de datos', actividad:'72300'},
    { nombre : 'Servicios relacionados con bases de datos', actividad:'72400'},
    { nombre : 'Servicios de mantenimiento y reparación de maquinaria de oficina, contabilidad e informática', actividad:'72500'},
    { nombre : 'Otras actividades de informática', actividad:'72900'},
    { nombre : 'Servicio de Investigación y desarrollo en  Ciencias Naturales ', actividad:'73101'},
    { nombre : 'Servicio de Investigación y desarrollo en Ingeniería', actividad:'73102'},
    { nombre : 'Investigaciones y desarrollo experimental en el campo de las Ciencias Sociales y las Humanidades', actividad:'73200'},
    { nombre : 'Servicios jurídicos', actividad:'74110'},
    { nombre : 'Servicios de contabilidad, teneduría de libros y auditoría; asesoramiento en materia de impuestos', actividad:'74120'},
    { nombre : 'Estudios de mercado y realización de encuestas de opinión pública', actividad:'74130'},
    { nombre : 'Servicio de asesoramiento, orientación y gestión empresarial ', actividad:'74140'},
    { nombre : 'Servicios de arquitectura', actividad:'74211'},
    { nombre : 'Servicios de ingeniería', actividad:'74212'},
    { nombre : 'Servicios geológicos y  de prospección minera', actividad:'74213'},
    { nombre : 'Servicios geológicos y  de prospección petrolera', actividad:'74214'},
    { nombre : 'Otros servicios de actividades técnicas', actividad:'74219'},
    { nombre : 'Servicios de ensayos y análisis técnicos', actividad:'74220'},
    { nombre : 'Servicios de publicidad', actividad:'74300'},
    { nombre : 'Obtención y dotación de personal', actividad:'74910'},
    { nombre : 'Servicios de transporte de caudales y objetos de valor', actividad:'74921'},
    { nombre : 'Servicios de investigación y seguridad personal ', actividad:'74922'},
    { nombre : 'Servicios de limpieza de edificios', actividad:'74930'},
    { nombre : 'Servicios de fotografía ', actividad:'74940'},
    { nombre : 'Servicios de envase y empaque ', actividad:'74950'},
    { nombre : 'Servicios de fotocopias, impresión heliográfica y otras formas de reproducción', actividad:'74960'},
    { nombre : 'Otros servicios empresariales ncp', actividad:'74990'},
    { nombre : 'Administración Pública ', actividad:'75110'},
    { nombre : 'Regulación de las actividades de organismos que prestan servicios sanitarios, educativos, culturales y otros servicios sociales, excepto servicios de seguridad social', actividad:'75120'},
    { nombre : 'Regulación y facilitación de la actividad económica', actividad:'75130'},
    { nombre : 'Actividades de servicios auxiliares para la administración pública en general', actividad:'75140'},
    { nombre : 'Relaciones exteriores', actividad:'75210'},
    { nombre : 'Actividades de defensa', actividad:'75220'},
    { nombre : 'Actividades de servicios judiciales y de justicia', actividad:'75231'},
    { nombre : 'Actividades de servicios de orden público y de seguridad', actividad:'75232'},
    { nombre : 'Actividades de planes de seguridad social de afiliación obligatoria', actividad:'75300'},
    { nombre : 'Educación  inicial', actividad:'80101'},
    { nombre : 'Educación primaria', actividad:'80102'},
    { nombre : 'Educación secundaria de formación general', actividad:'80210'},
    { nombre : 'Educación secundaria de formación técnica y profesional', actividad:'80220'},
    { nombre : 'Formación superior no universitaria', actividad:'80301'},
    { nombre : 'Educación superior universitaria', actividad:'80302'},
    { nombre : 'Educación superior de especialización y postgrado', actividad:'80303'},
    { nombre : 'Educación de adultos', actividad:'80901'},
    { nombre : 'Enseñanza comercial, contable y secretariado', actividad:'80902'},
    { nombre : 'Enseñanza de artes', actividad:'80903'},
    { nombre : 'Enseñanza para la prestación de servicios (hotelería, repostería, confección, peluquería , etc)', actividad:'80904'},
    { nombre : 'Enseñanza para la conducción de automotores y aviones', actividad:'80905'},
    { nombre : 'Enseñanza de idiomas', actividad:'80906'},
    { nombre : 'Enseñanza de informática y computación', actividad:'80907'},
    { nombre : 'Enseñanza para personas discapacitadas', actividad:'80908'},
    { nombre : 'Otras enseñanzas ncp', actividad:'80909'},
    { nombre : 'Servicios hospitalarios', actividad:'85110'},
    { nombre : 'Servicio de atención médica en clínicas', actividad:'85121'},
    { nombre : 'Servicios de consultas médicas', actividad:'85122'},
    { nombre : 'Servicios de odontología', actividad:'85123'},
    { nombre : 'Servicios de laboratorios clínicos', actividad:'85191'},
    { nombre : 'Servicios de centros radiológicos', actividad:'85192'},
    { nombre : 'Servicios de centros terapéuticos ', actividad:'85193'},
    { nombre : 'Otros servicios relacionados con la salud humana ncp', actividad:'85199'},
    { nombre : 'Servicios  veterinarios', actividad:'85200'},
    { nombre : 'Servicios de asistencia social a niños con alojamiento', actividad:'85311'},
    { nombre : 'Servicios de asistencia social a jóvenes con alojamiento', actividad:'85312'},
    { nombre : 'Servicios de asistencia social a ancianos con alojamiento', actividad:'85313'},
    { nombre : 'Servicios de asistencia social a personas discapacitadas con alojamiento', actividad:'85314'},
    { nombre : 'Servicios de asistencia social en centros de rehabilitación', actividad:'85315'},
    { nombre : 'Otros servicios de asistencia social con alojamiento ncp', actividad:'85319'},
    { nombre : 'Servicios sociales a niños sin alojamiento', actividad:'85321'},
    { nombre : 'Servicios sociales de orientación y asesoramiento sin alojamiento', actividad:'85322'},
    { nombre : 'Servicios sociales de orientación familiar', actividad:'85323'},
    { nombre : 'Servicios sociales a personas discapacitadas sin alojamiento', actividad:'85324'},
    { nombre : 'Servicios de asistencia social en centros de rehabilitación', actividad:'85325'},
    { nombre : 'Otros servicios de asistencia social sin alojamiento ncp', actividad:'85329'},
    { nombre : 'Servicios de depuración de aguas residuales y alcantarillado y cloacas', actividad:'90001'},
    { nombre : 'Servicios de limpieza de vías públicas y tratamiento de desechos', actividad:'90002'},
    { nombre : 'Servicios de organizaciones empresariales y de empleadores', actividad:'91110'},
    { nombre : 'Servicios de organizaciones profesionales', actividad:'91120'},
    { nombre : 'Servicios de sindicatos', actividad:'91200'},
    { nombre : 'Servicios de organizaciones religiosas', actividad:'91910'},
    { nombre : 'Servicios de organizaciones políticas', actividad:'91920'},
    { nombre : 'Servicios de otras asociaciones ncp', actividad:'91990'},
    { nombre : 'Producción y distribución de filmes y cintas de vídeo', actividad:'92110'},
    { nombre : 'Exhibición de filmes y videocintas', actividad:'92120'},
    { nombre : 'Servicios de radio', actividad:'92131'},
    { nombre : 'Servicios de programas de televisión', actividad:'92132'},
    { nombre : 'Creación e interpretación artística y literaria', actividad:'92141'},
    { nombre : 'Producción de espectáculos', actividad:'92142'},
    { nombre : 'Otras actividades relacionadas con el espectáculo', actividad:'92143'},
    { nombre : 'Servicios de salones de baile, discotecas y similares', actividad:'92191'},
    { nombre : 'Otros servicios de entretenimiento ncp', actividad:'92199'},
    { nombre : 'Servicio de agencias de noticias', actividad:'92200'},
    { nombre : 'Servicios de bibliotecas y archivos', actividad:'92310'},
    { nombre : 'Servicios de museos y preservación de lugares y edificios históricos', actividad:'92320'},
    { nombre : 'Servicios de jardines botánicos y zoológicos y de parques nacionales', actividad:'92330'},
    { nombre : 'Servicios de organización, dirección y gestión de prácticas deportivas y explotación de las instalaciones', actividad:'92411'},
    { nombre : 'Servicios prestados por escuelas, profesionales y técnicos, para la realización de prácticas deportivas', actividad:'92412'},
    { nombre : 'Servicios de esparcimiento relacionadas con juegos de azar y apuestas', actividad:'92491'},
    { nombre : 'Servicios de salones de juegos', actividad:'92492'},
    { nombre : 'Otros servicios de actividades de esparcimiento ncp', actividad:'92499'},
    { nombre : 'Servicios de lavado y limpieza de prendas de tela y de piel, incluso la limpieza en seco', actividad:'93010'},
    { nombre : 'Servicios de peluquería y otros tratamientos de belleza', actividad:'93020'},
    { nombre : 'Servicios funerarios y actividades conexas', actividad:'93030'},
    { nombre : 'Servicio para el mantenimiento físico-corporal', actividad:'93091'},
    { nombre : 'Otros servicios ncp', actividad:'93099'},
    { nombre : 'Servicio de hogares privados que contratan servicio doméstico', actividad:'95000'},
    { nombre : 'Servicio de organizaciones y órganos extraterritoriales', actividad:'98000'},
    { nombre : 'Jubilados o rentistas', actividad:'99001'},
    { nombre : 'Estudiantes', actividad:'99002'},
    { nombre : 'Amas de casa', actividad:'99003'},
    
];

router.post('/caedec/insercion-masiva', authRequired, async (req, res) => {
    try {
        await sequelize.authenticate(); // Conectar a la base de datos
        await Caedec.bulkCreate(
            registros.map(registro => ({
                ...registro,
                fecha_registro: new Date(),
                fecha_actualizacion: new Date(),
            })),
            { ignoreDuplicates: true } // Ignora duplicados si es necesario
        );
        res.status(201).json({ message: 'Registros insertados correctamente.' });
    } catch (error) {
        console.error('Error al insertar registros:', error);
        res.status(500).json({ error: 'Error al insertar registros' });
    }
});


export default router